name: Packer check workflow
on:
  pull_request:
    branches: [main]
jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
            version: 1.11.2
      - name: Zip webapp
        run: |
          [ -e webapp.zip] && rm -rf webapp.zip
          zip -r webapp.zip . -x ".git/*" ".github/*"
      - name: packer init
        run: packer init .
      - name: create variables.pkrvars.hcl
        run: |
          cat <<EOF > variables.pkrvars.hcl
          ${{ secrets.PKR_VARS }}
          EOF 
      - name: packer fmt
        run: packer fmt -check -recursive .
      - name: packer validate
        run: packer validate .