name: Packer build workflow
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - a05-demo
jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: create .env
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
      - name: install dependencies
        run: npm install
      - name: install aws cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}       
      - name: install postgres
        uses: ikalnytskyi/action-setup-postgres@v6
        with:
          username: ${{ secrets.PSQL_USER }}
          password: ${{ secrets.PSQL_PASS }}
          database: ${{ secrets.PSQL_DBNAME }}
          port: 5432
        id: postgres
      - name: integration test
        run: npm test
        env:
          POSTGRES_HOST: localhost
          PSQL_USER: ${{ secrets.PSQL_USER }}
          PSQL_PASS: ${{ secrets.PSQL_PASS }}
          PSQL_DBNAME: ${{ secrets.PSQL_DBNAME }}
          TEST_CHANGE_FIRSTNAME: ${{ secrets.TEST_CHANGE_FIRSTNAME}}
          TEST_CHANGE_PASSWORD: ${{ secrets.TEST_CHANGE_PASSWORD }}
          TEST_POSTDATA_EMAIL: ${{ secrets.TEST_POSTDATA_EMAIL }}
          TEST_POSTDATA_FIRSTNAME: ${{ secrets.TEST_POSTDATA_FIRSTNAME }}
          TEST_POSTDATA_LASTNAME: ${{ secrets.TEST_POSTDATA_LASTNAME }}
          TEST_POSTDATA_PASS: ${{ secrets.TEST_POSTDATA_PASS }}
          PORT: 5000
      - name: check completion
        run: echo "Check completion"
      - name: Zip webapp
        run: |
          [ -e webapp.zip] && rm -rf webapp.zip
          zip -r webapp.zip . -x ".git/*" ".github/*" ".env"
      - name: create variables.pkrvars.hcl
        run: |
          echo "${{ secrets.PKR_VARS }}" > variables.pkrvars.hcl      
      - name: setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
            version: 1.11.2
      - name: packer init
        run: packer init .
      - name: packer fmt
        run: packer fmt -check -recursive .
      - name: packer validate
        run: packer validate -var-file=variables.pkrvars.hcl .
      - name: packer build
        run: |
          packer build \
          -var-file=variables.pkrvars.hcl .